---
title: "Feature Engineering"
date: "2025-08-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(purrr)
```
# Importing Raw Data
```{r}
burundi_crs <- readRDS("../data/Raw Data/bdi_result_crs.rds")
colombia_crs <- readRDS("../data/Raw Data/col_result_crs.rds")
```

```{r}
burundi_mptf <- readRDS("../data/Raw Data/bdi_result_mptf_nogovsig.rds")
colombia_mptf <- readRDS("../data/Raw Data/col_result_mptf_nogovsig.rds")
```

# Preprocessing
```{r}
dataframe <- c("crs", "mptf")
country_list <- c("burundi", "colombia")

for (DATASET in dataframe) {

for (COUNTRY in country_list) {
  
  COUNTRY_DATASET <- get(paste0(COUNTRY,"_", DATASET))

years <- names(COUNTRY_DATASET[["edge_lists"]]) %>% 
  as.numeric() %>% 
  sort()

first_year <- min(years)
last_year  <- max(years)

# subsetting country crs data by year
for (i in first_year:last_year) {
  COUNTRY_DATASET_i <- COUNTRY_DATASET[["edge_lists"]][[as.character(i)]]
  
  COUNTRY_DATASET_i <- COUNTRY_DATASET_i %>%
    mutate(Country = COUNTRY, Year = i, data = DATASET)
  
  assign(paste0(COUNTRY,"_", DATASET,"_", i), COUNTRY_DATASET_i)
}

# appending to make 1 per country per dataset
assign(
  paste0(COUNTRY, "_", DATASET, "_all_years"),
  bind_rows(mget(paste0(COUNTRY, "_", DATASET, "_", first_year:last_year)))
)

# cleaning the environment
rm(list = paste0(COUNTRY, "_", DATASET, "_", first_year:last_year), COUNTRY_DATASET_i, COUNTRY_DATASET)
rm(list = paste0(COUNTRY,"_",DATASET))
}
}
```



```{r}
country_list <- c("burundi", "colombia")

for (COUNTRY in country_list) {
  
  COUNTRY_crs <- get(paste0(COUNTRY, "_crs"))

years <- names(COUNTRY_crs[["edge_lists"]]) %>% 
  as.numeric() %>% 
  sort()

first_year <- min(years)
last_year  <- max(years)

# subsetting country crs data by year
for (i in first_year:last_year) {
  COUNTRY_crs_i <- COUNTRY_crs[["edge_lists"]][[as.character(i)]]
  
  COUNTRY_crs_i <- COUNTRY_crs_i %>%
    mutate(Country = COUNTRY, Year = i)
  
  assign(paste0(COUNTRY, "_crs_", i), COUNTRY_crs_i)
}

# appending to make 1 crs dataset per country
assign(
  paste0(COUNTRY, "_crs_all_years"),
  bind_rows(mget(paste0(COUNTRY, "_crs_", first_year:last_year)))
)

# cleaning the environment
rm(list = paste0(COUNTRY, "_crs_", first_year:last_year), COUNTRY_crs_i, COUNTRY_crs)
}
```
